version: '3'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"

  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: SA
      POSTGRES_PASSWORD: Heureka10
      POSTGRES_DB: omn
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5435:5432"
    restart: unless-stopped

  authorization-service:
    container_name: authorization-service
    depends_on:
      - postgres
    build:
      context: ../authorization-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./authorization-service:/data/logs

  hashtranslator-service:
    container_name: hashtranslator-service
    depends_on:
      - mongodb
    build:
      context: ../hashtranslator-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./hashtranslator-service:/data/logs